### PR TITLE
feature/version-command

### PR DESCRIPTION
**Pull request by azamanaza**
# Changes
- fetch version form package
- add version command

### CODE REVIEW

**Review by zacariec — CHANGES_REQUESTED** [review]
Looks good however:
- need to remove white-space on line 36 for ./bin/cli.js and just have cli.version() above cli.parse()
- Probably don't need to require it in ./bin/lib/index.js - just require it in ./bin/cli.js

Then it should be good to go 👍

**Comment by azamanaza** [comment]
Applied change request.

**Comment by azamanaza** [comment]
> Looks good however:
> 
> * need to remove white-space on line 36 for ./bin/cli.js and just have cli.version() above cli.parse()
> * Probably don't need to require it in ./bin/lib/index.js - just require it in ./bin/cli.js
> 
> Then it should be good to go 👍

Applied change request

**Review by zacariec — APPROVED** [review]
Looks good thanks mate, will bundle this in with 1.0.6

**Comment by zacariec** [comment]
Approved merging to 1.0.6
Locking thread

**Pull request merged**
